$(function(){
	//--
	$('.classLayer').find('li:last').css('background','none');
	$('.indexFoot_01').find('.content:last').css('background','none');
	$('.productClass').find('li:last').css('background','none');
	$('.Purchase_03').find('tr:last').find('td').css('background','none');
	$('.Market_03').find('dl').find('dd:last').css('border','0px');
	$('.Industry_01').find('li:last').css('background','none');
	$('.Industry_03').find('tr:last').find('td').css('background','none');
	$('.Industry_07').find('li:last').css('background','none');
	$('.nav').find('li:last').css('background','none');
	$('.regHead2').find('.btn3').find('li:last').css('background','none');
	$('.businessTop').find('li:last').css('background','none');
	$('.releaseOk').find('tr:last').find('td').css('background','none');
	$('.businessState2').find('tr:last').find('td').css('background','none');
	//--选项卡
	$('.tabContentDiv').find('.tabContent:first').show();
	$('.tab').each(function(i){
		$(this).find('li').each(function(ii){
			$(this).hover(
			function(){
				$('.tab').eq(i).find('li').removeClass('liNow');
				$(this).addClass('liNow');
				$('.tabContentDiv').eq(i).find('.tabContent').hide();
				$('.tabContentDiv').eq(i).find('.tabContent').eq(ii).show();
				},
			function(){}
				)
			})
		})
	//--选项卡2
	$('.tabContentDiv2').find('.tabContent2:first').show();
	$('.tab2').each(function(i){
		$(this).find('li').each(function(ii){
			$(this).hover(
			function(){
				$('.tab2').eq(i).find('li').removeClass('liNow');
				$(this).addClass('liNow');
				$('.tabContentDiv2').eq(i).find('.tabContent2').hide();
				$('.tabContentDiv2').eq(i).find('.tabContent2').eq(ii).show();
				},
			function(){}
				)
			})
		})
	//--首页资讯tab
	$('.tabContentDivNews').find('.tabContent:first').show();
	$('.tabNews').each(function(i){
		$(this).find('li a').each(function(ii){
			$(this).hover(
			function(){
				$('.tabNews').eq(i).find('li').removeClass('liNow');
				$(this).parent().addClass('liNow');
				$('.tabContentDivNews').eq(i).find('.tabContent').hide();
				$('.tabContentDivNews').eq(i).find('.tabContent').eq(ii).show();
				},
			function(){}
				)
			})
		})
	//--首页买家服务
	//--首页行业资讯焦点图
	//--首页今日行情
	//--独家冠名
	//--市场推荐
	//--您可能感兴趣的货源
	//--首页登录等按钮
	//--首页右侧按钮（复杂特效，多个效果组成）
	$('.sideBar').find('h1').toggle(
	   function(){
		   $('.sideBar').height(18);
		   },
	   function(){
		   $('.sideBar').height(500);
		   }
	)
	if($('.sideBar').length>0){
	  var sideBarTop=$('.sideBar').offset().top;
	  $(window).scroll(function(){
		  if($(window).scrollTop()>630){
			  $('.sideBar').addClass('sideBarNow');
                          $('.leftBar').addClass('leftBarNow');
			  }else{
				  $('.sideBar').removeClass('sideBarNow');
                                  $('.leftBar').removeClass('leftBarNow');
				  }
		  //--
		  $('.sideBar').find('.list').find('a').each(function(i){
			  if($(window).scrollTop()>$('.indexFoot').eq(i).offset().top-50){
				  $('.sideBar').find('.list').find('a').removeClass('aNow');
				  $('.sideBar').find('.list').find('a').eq(i).addClass('aNow');
				  }
			  })
		  })
	  $('.sideBar').find('.list').find('a').each(function(i){
		  $(this).click(function(){
			  $('.sideBar').find('.list').find('a').removeClass('aNow');
			  $(this).addClass('aNow');
			  $('body,html').animate({scrollTop: $('.indexFoot').eq(i).offset().top}, 500);
			  })
		  })
	  $('.topA').click(function(){
		  $('body,html').animate({scrollTop: 0}, 500);
		  })
	}
	//--行业分类（复杂特效）
	$('.classLayer2').find('.close').click(function(){
		$('.classLayer2').hide();
		})
	$('.classLayer2').each(function(i){
	$(this).hover(
	   function(){
		   $(this).show();
		   $('#classLayer').find('.list').show();
		   $('.classLayer').find('li').eq(i).find('a').addClass('aNow');
		   },
	   function(){
		   $('#classLayer').find('.list').hide();
		   $('.classLayer2').hide();
		   $('.classLayer').find('li').find('a').removeClass('aNow');
		   }
	)
	})
	$('.classLayer').find('li').find('a').each(function(i){
		$(this).hover(
		   function(){
			   $('.classLayer').find('li').find('a').removeClass('aNow');
			   $('.classLayer').find('li').find('a').eq(i).addClass('aNow');
			   $('.classLayer2').hide();
			   $('.classLayer2').eq(i).show();
			   },
		   function(){
			   $('.classLayer2').hide();
			   $('.classLayer').find('li').find('a').removeClass('aNow');
			   }
		)
		})
	$('#classLayer').hover(
	   function(){
		   $('.classLayer').find('li').find('a').removeClass('aNow');
		   $(this).find('.list').show();
		   },
	   function(){
		   $(this).find('.list').hide();
		   $('.classLayer2').hide();
		   $('.classLayer').find('li').find('a').removeClass('aNow');
		   }
	)
	//--首页优质供应商
	$('.indexFoot_03').find('.list').each(function(){
		$(this).slide({mainCell:"ul",autoPlay:true,effect:"topMarquee",vis:6,interTime:50,trigger:"click"});
		})
	//--首页热门供应顶部图片
	$('.indexFoot_02').find('img').hover(
	   function(){
		   $(this).fadeTo(200,0.6);
		   },
	   function(){
		   $(this).fadeTo(200,1);
		   }
	)
	//--行业分类图片
	$('.classLayer2').find('img').hover(
	   function(){
		   $(this).fadeTo(200,0.6);
		   },
	   function(){
		   $(this).fadeTo(200,1);
		   }
	)
	//--顶部下拉
	$('.topDiv').find('.fr').find('li').each(function(i){
		$(this).width($(this).width());
		$(this).find('a').width($(this).width()-12);
		$(this).find('a.hassub').hover(
		   function(){
			   $('.topLayer').eq(i).css('left',$(this).offset().left);
			   $('.topLayer').eq(i).show();
			   },
		   function(){
			   $('.topLayer').eq(i).hide();
			   }
		)
		})
	$('.topLayer').each(function(i){
	$(this).hover(
		   function(){
			   $('.topDiv').find('.fr').find('li').eq(i).find('a').addClass('aNow');
			   $(this).show();
			   },
		   function(){
			   $('.topDiv').find('.fr').find('li').find('a').removeClass('aNow');
			   $(this).hide();
			   }
		)
	})
	//--供应页面列表
	$('.Supply_01').find('li').hover(
	   function(){
		   $(this).addClass('liNow');
		   },
	   function(){
		   $(this).removeClass('liNow');
		   }
	)
	//--供应页面放大图片
	$('.Supply_01').find('li').each(function(i){
		$(this).find('.imgDiv').hover(
		   function(){
			   $('.SupplyBigImg').css('left',$(this).offset().left+172);
			   $('.SupplyBigImg').css('top',$(this).offset().top-10);
			   $('.SupplyBigImg').hide();
			   },
		   function(){
			   $('.SupplyBigImg').hide();
			   }
		)
		})
	//--js下拉选择框
	//--供应列表页大图
	$('.Supply2').find('li').hover(
	   function(){
		   $(this).addClass('liNow');
		   },
	   function(){
		   $(this).removeClass('liNow');
		   }
	)
	//--供应详情页关闭按钮
	$('.supplyTips').find('.close').click(function(){
		$('.supplyTips').hide();
		})
	//--供应页面详情页焦点图
	//--求购页面顶部菜单
//	$('.nav2').find('li').each(function(){
//		$(this).width($(this).width());
//		})
	//--求购首页焦点图
	//--成交速递
	//--求购信息
	//--求购信息首页分类
	$('.Purchase_04').find('.box').hover(
	   function(){
		   $(this).addClass('boxNow');
		   },
	   function(){
		   $(this).removeClass('boxNow');
		   }
	)
	//--求购信息首页分类选项卡
	//--求购信息首页成交案例
	//--求购发送成功
	//--企业首页焦点图
	//--企业首页市场
	$('.company_06').find('li:first').addClass('liNow');
	$('.company_06').each(function(i){
		$(this).find('li').hover(
		   function(){
			   $('.company_06').eq(i).find('li').removeClass('liNow');
			   $(this).addClass('liNow');
			   },
		   function(){}
		)
		})
	//--公司列表
	$('.companyList').find('li').hover(
	   function(){
		   $(this).addClass('liNow');
		   },
	   function(){
		   $(this).removeClass('liNow');
		   }
	)
	//--资讯首页焦点图
	//--资讯首页行业资讯
	//--资讯首页专题
	//--资讯首页新闻图集
	//--行情报价首页今日行情
	//--行情报价首页焦点图
	//--行情报价首页选项卡
	//--行情报价首页行情评论
	//--今日行情列表页
	$('.QuotationList').find('li').hover(
	   function(){
		   $(this).addClass('liNow');
		   },
	   function(){
		   $(this).removeClass('liNow');
		   }
	)
//--资讯详情页 标签个数判断
//    $('.newShow_03 .list').addClass('tagbg'+$(".newShow_03 .list ul li").length);
	//--展会首页焦点图
	//--展会首页选项卡
	//--展会列表
	$('.ExhibitionList').find('li').hover(
	   function(){
		   $(this).addClass('liNow');
		   },
	   function(){
		   $(this).removeClass('liNow');
		   }
	)
	//--展会在线报名
	//--展会在线报名成功
	$('.ExhibitionLayer').find('.btn1').click(function(){
		$('.ExhibitionLayer').hide();
		$('.ExhibitionOk').show();
		})
	//--市场首页焦点图
	//--市场首页市场考察专题
	//--市场列表页
	$('.MarketList').find('li').hover(
	   function(){
		   $(this).addClass('liNow');
		   },
	   function(){
		   $(this).removeClass('liNow');
		   }
	)
	//--市场概貌同行市场推荐
	//--市场概貌焦点图(复杂特效)
	//--市场供应求购
	//--中国再生网提示弹出层
	//--照片点击排行
	$('.photoRank').each(function(i){
	$(this).find('li').hover(
	   function(){
		   $('.photoRank').eq(i).find('li').removeClass('liNow');
		   $(this).addClass('liNow');
		   },
	   function(){}
	)
	})
	//--
	$('.photoHead').find('.fr').find('a:last').css('background','none');
	//--照片详情（复杂特效）
	var photoShowNow=1;
	$('.photoShow').find('.num').html("<span>1</span>"+$('.photoShow').find('.bigImg').find('li').length);
	$('.photoShow').find('.next').click(function(){
		imgScrollRight2($('.photoShow').find('.bigImg').find('.list'),$('.photoShow').find('.bigImg').find('li').length-1,998,0);
		imgScrollRight2($('.photoShow').find('.list2').find('.list'),$('.photoShow').find('.list2').find('li').length-1,925,2);
		imgScrollRight2($('.photoShow').find('.list3').find('.list'),$('.photoShow').find('.list3').find('li').length-6,143,3);
		$('.photoShow').find('.num').find('span').html(imgScrollNum2[0]+1);
		$('.photoShow').find('.list3').find('li').removeClass('liNow');
		$('.photoShow').find('.list3').find('li').eq(imgScrollNum2[0]).addClass('liNow');
		})
	$('.photoShow').find('.prev').click(function(){
		imgScrollLeft2($('.photoShow').find('.bigImg').find('.list'),$('.photoShow').find('.bigImg').find('li').length-1,998,0);
		imgScrollLeft2($('.photoShow').find('.list2').find('.list'),$('.photoShow').find('.list2').find('li').length-1,925,2);
		imgScrollLeft2($('.photoShow').find('.list3').find('.list'),$('.photoShow').find('.list3').find('li').length-6,143,3);
		$('.photoShow').find('.num').find('span').html(imgScrollNum2[0]+1);
		$('.photoShow').find('.list3').find('li').removeClass('liNow');
		$('.photoShow').find('.list3').find('li').eq(imgScrollNum2[0]).addClass('liNow');
		})
	$('.photoShow').find('.list3').find('li').each(function(i){
		$(this).click(function(){
			imgScrollNum2[0]=i;
			imgScrollNum2[2]=i;
			imgScrollNum2[3]=i;
			$('.photoShow').find('.num').find('span').html(imgScrollNum2[0]+1);
			$('.photoShow').find('.bigImg').find('.list').animate({scrollLeft: i*998}, 200);
			$('.photoShow').find('.list2').find('.list').animate({scrollLeft: i*925}, 200);
			$('.photoShow').find('.list3').find('li').removeClass('liNow');
			$('.photoShow').find('.list3').find('li').eq(imgScrollNum2[0]).addClass('liNow');
			})
		})
	//--专题首页焦点图
	//--专题列表页
	$('.topicsList').find('li').hover(
	   function(){
		   $(this).addClass('liNow');
		   },
	   function(){
		   $(this).removeClass('liNow');
		   }
	)
	//--行业分站焦点图
	//--行业分站废金属
	$('.Industry_05').find('li').hover(
	   function(){
		   $('.Industry_05').find('li').removeClass('liNow');
		   $(this).addClass('liNow');
		   },
	   function(){}
	)
	//--行业分站热门产品
	//--市场地图热门市场
	//--------新增js---------------------
	//--顶部输入框
	//--分类
	var sContentANow=100;
	$('.sContentA').each(function(i){
		$(this).click(function(){
			   if(sContentANow==i){
				   $('.productClassIco').hide();
				   $('.sContent').hide();
				   sContentANow=100;
				   }else{
					   sContentANow=i;
					   $('.productClassIco').css('left',$(this).offset().left+($(this).width()-8)/2);
					   $('.productClassIco').css('top',$(this).offset().top+21);
					   $('.productClassIco').show();
					   $('.sContent').hide();
					   $('.sContent').eq(i).show();
					   }
			   })
		})
	//--找加密码选择方式
	//--留言发布成功
	//--标题颜色
	$('.release').find('.li_03').find('.tips').find('img').toggle(
	  function(){
		  $('.release').find('.li_03').find('.imgDiv').show();
		  },
	  function(){
		  $('.release').find('.li_03').find('.imgDiv').hide();
		  }
	)
	//--快速发布登录
	//--快速发布注册
	//--关于我们下拉菜单
	$('.aboutNav').find('li').hover(
	   function(){
		   $(this).find('a:first').addClass('aNow1');
		   $(this).find('div').show();
		   },
	   function(){
		   $(this).find('a:first').removeClass('aNow1');
		   $(this).find('div').hide();
		   }
	)
	//--联系我们
	$('.Contact').find('li').hover(
	   function(){
		   $(this).find('.box').fadeIn(200);
		   },
	   function(){
		   $(this).find('.box').fadeOut(200);
		   }
	)
	//--会员商务中心左侧菜单
	$('.businessSide2').find('li').each(function(i){
		$(this).find('h2').click(function(){
			$('.businessSide2').find('li').removeClass('liNow');
			$('.businessSide2').find('li').eq(i).addClass('liNow');
			$('.businessSide2').find('li').find('a').removeClass('aNow');
			$(this).find('a').addClass('aNow');
			})
		})
	$('.businessTab2').find('li').each(function(i){
		$(this).find('a').click(function(){
                        $('.businessSide2').find('li').find('a').removeClass('aNow');
			$('.businessSide2').find('li').eq(i).find('a').addClass('aNow');
			})
		})
	//--发布行情成功弹出层
	//--发布行情修改弹出层
	//--产品分类
	$('.shopsSide_03').find('li').each(function(i){
		$(this).find('em').click(function(){
			$('.shopsSide_03').find('li').removeClass('liNow');
			$('.shopsSide_03').find('li').eq(i).addClass('liNow');
			$('.shopsSide_03').find('li').find('a').removeClass('aNow');
			$(this).find('a').addClass('aNow');
			})
		})
	//--商铺二级下拉菜单
	$('.sNav_2A').each(function(i){
		$(this).hover(
		   function(){
			   $('.sNav_2').eq(i).show();
			   },
		   function(){
			   $('.sNav_2').eq(i).hide();
			   }
		)
		})
	$('.sNav_2').each(function(i){
		$(this).hover(
		   function(){
			   $('.sNav_2A').eq(i).addClass('aNow1');
			   $(this).show();
			   },
		   function(){
			   $('.sNav_2A').removeClass('aNow1');
			   $(this).hide();
			   }
		)
		})
	//--天津天宇公司低价出售再生胶
	$('.shopsProductShow_01').find('.fl').find('li').hover(
	   function(){
		   $('.shopsProductShow_01').find('.fl').find('.bigImg').find('img').attr('src',$(this).find('img').attr('src'));
		   },
	   function(){}
	)
	//--相册详情
	//--专题首页单位
	$('.topicsIndex_08').find('li').hover(
		   function(){
			   $(this).find('.mouse').fadeIn(200);
			   },
		   function(){
			   $(this).find('.mouse').fadeOut(200);
			   }
		)
	//--赞助与支持
	//--我要赞助
	$('.topicsSponsor2').find('.list').find('li').hover(
		   function(){
			   $(this).find('p').fadeIn(200);
			   },
		   function(){
			   $(this).find('p').fadeOut(200);
			   }
		)
	//--会场服务选项卡
	//--会场议程选项卡
	//--专题页面联系我们
	$('.topicsContact').find('li').hover(
		   function(){
			   $(this).find('dl').fadeIn(200);
			   },
		   function(){
			   $(this).find('dl').fadeOut(200);
			   }
		)
	//--
	$('.topicsIndex2_1').find('.content').fadeTo(10,0.6);
	//--专题图集
	//--表单文字对齐（复杂效果）
	//--
	var fadeFlashTime=new Array();
	$('.fadeFlash').find('li:first').fadeIn(500);
	$('.fadeFlash').each(function(i){
		fadeFlashTime[i] = setInterval("fadeFlashFun("+i+")",5000);
		$(this).find('.btnDiv').find('span').each(function(ii){
			$(this).hover(
			function(){
				clearInterval(fadeFlashTime[i]);
				$('.fadeFlash').eq(i).find('.btnDiv').find('span').removeClass('spanNow');
				$(this).addClass('spanNow');
				$('.fadeFlash').eq(i).find('li').eq(fadeFlashNow[i]).fadeOut(500);
				fadeFlashNow[i]=ii;
				$('.fadeFlash').eq(i).find('li').eq(fadeFlashNow[i]).fadeIn(500);
				fadeFlashTime[i] = setInterval("fadeFlashFun("+i+")",5000);
				},
			function(){}
				)
			})
		$(this).find('.rightBtn').click(function(){
			clearInterval(fadeFlashTime[i]);
			$('.fadeFlash').eq(i).find('.btnDiv').find('span').removeClass('spanNow');
			$('.fadeFlash').eq(i).find('li').eq(fadeFlashNow[i]).fadeOut(500);
			if(fadeFlashNow[i]<$('.fadeFlash').eq(i).find('li').length-1){
				fadeFlashNow[i]++;
				}else{
					fadeFlashNow[i]=0;
					}
			$('.fadeFlash').eq(i).find('.btnDiv').find('span').eq(fadeFlashNow[i]).addClass('spanNow');
			$('.fadeFlash').eq(i).find('li').eq(fadeFlashNow[i]).fadeIn(500);
			fadeFlashTime[i] = setInterval("fadeFlashFun("+i+")",5000);
			})
		$(this).find('.leftBtn').click(function(){
			clearInterval(fadeFlashTime[i]);
			$('.fadeFlash').eq(i).find('.btnDiv').find('span').removeClass('spanNow');
			$('.fadeFlash').eq(i).find('li').eq(fadeFlashNow[i]).fadeOut(500);
			if(fadeFlashNow[i]>0){
				fadeFlashNow[i]--;
				}else{
					fadeFlashNow[i]=$('.fadeFlash').eq(i).find('li').length-1;
					}
			$('.fadeFlash').eq(i).find('.btnDiv').find('span').eq(fadeFlashNow[i]).addClass('spanNow');
			$('.fadeFlash').eq(i).find('li').eq(fadeFlashNow[i]).fadeIn(500);
			fadeFlashTime[i] = setInterval("fadeFlashFun("+i+")",5000);
			})
		})
	//
	$('.topForm #destoon_select').hover(
	   function(){
		   $('.topForm #search_module').show();
		   },
	   function(){
		   $('.topForm #search_module').hide();
		   }
	)
	//--关于我们产品选项卡
	$('.aboutTabContentDiv').find('.tabContent:first').show();
	$('.aboutTab').each(function(i){
		$(this).find('li').each(function(ii){
			$(this).hover(
			function(){
                            $(this).parent().parent().attr('id',$(this).attr('rel'));
				$('.aboutTab').eq(i).find('li').removeClass('liNow');
				$(this).addClass('liNow');
				$('.aboutTabContentDiv').eq(i).find('.tabContent').hide();
				$('.aboutTabContentDiv').eq(i).find('.tabContent').eq(ii).show();
				},
			function(){}
				)
			})
		})
//	$('.SupplySideImg li.item').hover(
//	   function(){
//		   $(this).find('img').hide();
//                   $(this).find('.sub').show();
//		   },
//	   function(){
//		   $(this).find('img').show();
//                   $(this).find('.sub').hide();
//		   }
//	)
	})

            /*内部搜索*/
function setModule1(i, n) {Dd('destoon_search1').action = DTPath+'api/search.php';Dd('destoon_moduleid1').value = i;searchid = i;Dd('destoon_select1').value = n;$('#search_modules1').fadeOut('fast');}
